#!/bin/sh

html=$1
allowpath=$2
here=`pwd`

sub=`echo ${html} | awk -F / '{print $NF}' | awk -F _ '{print $1}'`
echo ${sub}
pdf=`echo $html | sed -e '/html/s//pdf/'`

cd ${allowpath}

width=`identify ${sub}* | grep -v parse | head -1 | awk '{print $3}' | awk -F x '{print $1}'`
height=`identify ${sub}* clin_array_scale* | grep -v parse | awk '{print $3}' | awk -F x '{sum+=$2}END{print sum}'`

cd ${here}

if [ `expr ${width} / ${height}` -ge 1 ]
then
	#wkhtmltopdf --load-media-error-handling skip --allow $allowpath -T 1mm -R 1mm -L 1mm -B 1mm --page-width 250mm --page-height 350mm $html $pdf
	wkhtmltopdf --load-media-error-handling skip --allow $allowpath -T 1mm -R 1mm -L 1mm -B 1mm --page-width 350mm --page-height 530mm $html $pdf
else
	wkhtmltopdf --load-media-error-handling skip --allow $allowpath -T 1mm -R 1mm -L 1mm -B 1mm --page-width 350mm --page-height 560mm $html $pdf
fi
